### ISSUE TITLE
Failed to initlalize the SSL layer

### ISSUE THREAD

**Issue by Manojkumar0308** [mobizt/ESP_SSLClient#13]
while just copied and paste the GSM.ino code I got above issue my LTE module get connected properly and also gprs also shows connected.

**Comment by mobizt** [comment]
I can confirm that this SSL client works well and is intensively tested 24/7 for years.

This library also works as the core of my popular libraries i.e. ESP-Firebase-Client, Firebase-ESP32, FirebaseClient, ESP-GSheet-Client, ESP-Gogle-Form-Client, ESP-LineNotify, and ESP-Mail-Client and all are work with TinyGSMClient without any problem.


Based on my experiences, you have to change your board power supply and cable.
