### ISSUE TITLE
SSL Error: BIGNUM error with ethernet client

### ISSUE THREAD

**Issue by tigershark224** [mobizt/ESP_SSLClient#18]
Hi! I am trying to make a request to raw githubusercontent to update esp32 firmware ota over ethernet. The client connects and starts downloading up to 5% of the firmware and then throws the following error and fails: SSL Error: BIGNUM - There is an invalid character in the digit string. Is thre something I'm missing? The following is the function I'm using:

int IEthernet::pullUpdate(const char* downloadURL) {
    Serial.println("---------------------------------");
    Serial.print("Connecting to server...");

    // Extract the hostname and path from the URL
    String url = downloadURL;
    int protocolEnd = url.indexOf("://");
    url.remove(0, protocolEnd + 3); // Remove "https://"
    int pathStart = url.indexOf('/');
    char* host = "raw.githubusercontent.com";
    String path = url.substring(pathStart);

    ESP_SSLClient ssl_client;
    ssl_client.setInsecure();
    ssl_client.setBufferSizes(2048, 512);  // Increase buffer sizes if needed
    ssl_client.setDebugLevel(3);
    ssl_client.setSessionTimeout(300);
    EthernetClient client;
    ssl_client.setClient(&client);

    if (!ssl_client.connect(host, 443)) {
        Serial.println("Connection failed!");
        return false;
    }

    // Send GET request
    ssl_client.print(String("GET ") + path + " HTTP/1.1\r\n" +
                     "Host: " + host + "\r\n" +
                     "Connection: keep-alive\r\n\r\n");

    // Read response headers
    size_t contentLength = 0;
    while (ssl_client.connected()) {
        String line = ssl_client.readStringUntil('\n');
        if (line.startsWith("Content-Length: ")) {
            contentLength = line.substring(16).toInt();
        }
        if (line == "\r") break;  // End of headers
    }

    if (contentLength == 0) {
        Serial.println("Content-Length not specified.");
        return false;
    }

    // Begin the update with the actual content length
    if (!Update.begin(contentLength)) { //contentLength
        Serial.println("Not enough space for firmware update.");
        return false;
    }

    // Allocate buffer for reading data
    uint8_t* buff = new uint8_t[512];
    if (!buff) {
        Serial.println("Failed to allocate memory for buffer");
        ssl_client.stop();
        return false;
    }

    // Start receiving the firmware binary data
    Serial.println("Receiving firmware...");
    size_t written = 0;
    unsigned long lastDataReceived = millis();
    
    while (ssl_client.connected() && written < contentLength) {
        size_t available = ssl_client.available();
        if (available > 0) {
            size_t bytesToRead = min(available, sizeof(buff));
            size_t bytesRead = ssl_client.readBytes(buff, bytesToRead);
            size_t bytesWritten = Update.write(buff, bytesRead);

            if (bytesWritten != bytesRead) {
                Serial.printf("Write error. Bytes read: %d, Bytes written: %d\n", bytesRead, bytesWritten);
                Update.abort();
                delete[] buff;
                return false;
            }

            written += bytesWritten;
            lastDataReceived = millis();  // Reset timeout on successful read
            ota_callback(written, contentLength);  // Update progress
        } else if (millis() - lastDataReceived > 5000) {
            Serial.println("Error: Connection timed out.");
            Update.abort();
            delete[] buff;
            return false;
        }
    }
    Serial.printf("Error code: %d\n", ssl_client.getLastSSLError());
    int sslErrorCode = ssl_client.getLastSSLError();
    printSSLError(sslErrorCode);
    //print if ssl client is connected
    Serial.printf("ssl client connected: %d\n", ssl_client.connected());
    Serial.printf("written: %d\n", written);

    // Complete the update
    if (Update.end() && Update.isFinished()) {
        delay(1000);
        ssl_client.stop();
        delete[] buff;
        Serial.println("Firmware update complete! Rebooting...");
        ESP.restart();
    } else {
        Serial.printf("Update failed. Error: %s\n", Update.errorString());
        Serial.printf("Content-Length: %d\n", contentLength);
        return false;
    }

    return true;
}

**Comment by mobizt** [comment]
You are posting the error that does not exist in this library code and `BearSSL` engine library code.

The error is from `mdebTLS` from your ESP32 `WiFiClientSecure/NetworkClientSecure` instead.
