### ISSUE TITLE
ESP_SSLClient with Ethernet Client connection delay

### ISSUE THREAD

**Issue by RazmigAvedis** [mobizt/ESP_SSLClient#2]
Hello!
I am trying to integrate the library with ESP32 + ethernet W5100 chip. I noticed that there is a connection delay of ~600ms everytime I connect to my HTTPS server with the function .connect(server,port). I need my firmware to be fast in transmitting data, so this delay is a problem for me. Is there a way to reduce this delay with session caching or connecting with a persistant connection?
Thank You.

**Comment by mobizt** [comment]
That is the time require to wait until the SSL handshake was done.

You should keep the session to open since connection established if you don't want SSL handshake to be done everytime you want to send/receive data.

**Comment by RazmigAvedis** [comment]
Also, if I want to check if the session did not disconnect and reconnect in the case the connection dropped, do I use an if condition on  `.connected()`?

**Comment by mobizt** [comment]
I forgot your question about session resumption.

You can save crypto settings in `BearSSL_Session` and resume it for faster handshake.

By define the `BearSSL_Session` in global and pass its pointer to `setSession` like this.

```cpp
BearSSL_Session session; //Global object

ssl_client.setSession(&session);// Assign its pointer
```

**Comment by RazmigAvedis** [comment]
> I forgot your question about session resumption.
> 
> You can save crypto settings in `BearSSL_Session` and resume it for faster handshake.
> 
> By define the `BearSSL_Session` in global and pass its pointer to `setSession` like this.
> 
> ```c++
> BearSSL_Session session; //Global object
> 
> ssl_client.setSession(&session);// Assign its pointer
> ```

Hello, I managed to reduce the connection time with this. but i have a question. I am getting the following error:
> ERROR.available: Cannot operate on a closed SSL connection.
> ERROR.available: Cannot operate on a closed SSL connection.
> ERROR.available: Cannot operate on a closed SSL connection.
> ERROR.available: Cannot operate on a closed SSL connection.
> ERROR.available: Cannot operate on a closed SSL connection.
> ERROR.available: Cannot operate on a closed SSL connection.
> ERROR.available: Cannot operate on a closed SSL connection.
> ERROR.available: Cannot operate on a closed SSL connection.
> ERROR.available: Cannot operate on a closed SSL connection.
> ERROR.available: Cannot operate on a closed SSL connection.
> ERROR.available: Cannot operate on a closed SSL connection.
> ERROR.available: Cannot operate on a closed SSL connection.
> ERROR.available: Cannot operate on a closed SSL connection.
> ERROR.available: Cannot operate on a closed SSL connection.
> ERROR.available: Cannot operate on a closed SSL connection.
> ERROR.available: Cannot operate on a closed SSL connection.

when this happens the firmware is getting stuck. What does this mean and how can I fix it?
Thanks alot!

**Comment by mobizt** [comment]
That is because the basic client is stopped or the `BearSSL` engine was already closed.

**Comment by mobizt** [comment]
This is the [session resumption](https://github.com/mobizt/ESP_SSLClient/blob/main/examples/session/session.ino) example.
