### ISSUE TITLE
JWT error

### ISSUE THREAD

**Issue by back920096** [mobizt/ESP_SSLClient#3]
Hello author, this problem occurs when reconnecting after a few days

Token error: code: -1, message: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values ​​in the JWT claim.

Will this problem occur if the gmtOffset setting of Firebase.setUDPClient does not match the current zone?
Or is there any part that needs special attention?

**Comment by mobizt** [comment]
You should post in the Firebase repo.

First, you should update the library to latest version.

The Firebase function `setUDPClient` is now deprecated.

Normally you can set the time zone via `FirebaseConfig` i.e., `config.time_zone` and  `config.daylight_offset`

You can set your device time yourself before calling `Firebase.begin` too which in this case, library will not touch your device time.

**Comment by back920096** [comment]
Thanks for the suggestion
After upgrading the version, I found some problems using the latest FCM
example.
fbdo.setEthernetClient(&eth, ETH_MAC, WIZNET_CS_PIN, WIZNET_RESET_PIN,
nullptr);
[image: image.png]
Problems using DHCP

Suwatchai K. ***@***.***> 於 2023年9月11日 週一 上午11:54寫道：

**Comment by mobizt** [comment]
I did not see the image. Please post your error here.

**Comment by mobizt** [comment]
Please go to GitHub and don't reply email directly.

**Comment by back920096** [comment]
Thanks for the suggestion
After upgrading the version, I found some problems using the latest FCM example.
fbdo.setEthernetClient(&eth, ETH_MAC, WIZNET_CS_PIN, WIZNET_RESET_PIN, nullptr);
Problems using DHCP
![image](https://github.com/mobizt/ESP_SSLClient/assets/28179698/f7a530bd-f1fd-4b6a-82e9-c47ed939d769)
![image](https://github.com/mobizt/ESP_SSLClient/assets/28179698/9cf1860c-53ae-4591-b29b-ec5e9b2f9080)

**Comment by mobizt** [comment]
See the example, ETH_MAC is actually `uint8_t` array, you can't use something like `std::initializer_list<uint8> `.

`uint8_t Eth_MAC[] = {0x02, 0xF0, 0x0D, 0xBE, 0xEF, 0x01};`

**Comment by back920096** [comment]
Thanks to the author for the reminder

![image](https://github.com/mobizt/ESP_SSLClient/assets/28179698/26794f19-aff5-4e87-acbf-f952b277853e)
Token error: code: -115, message: NTP server time reading cannot begin when valid time is required because of no WiFi capability/activity detected. Please set the library reference time manually using Firebase.setSystemTime

Use esp32s3+w5500
I would like to ask if the new version uses external Client. Do I need to set anything in firebaseFS.h?
![image](https://github.com/mobizt/ESP_SSLClient/assets/28179698/a6ca8bc2-e537-4cd4-98a0-c0f93524fee9)

I only saw w5500 with esp8266
Didn't see support for esp32

**Comment by mobizt** [comment]
The examples are [here](https://github.com/mobizt/Firebase-ESP-Client/tree/main/examples/ExternalClient/RTDB/Ethernet).

> NTP server time reading cannot begin when valid time is required because of no WiFi capability/activity detected. Please set the library reference time manually using Firebase.setSystemTime

As the error shown, you use external client (Ethernet) to connect, and your WiFi is also off, library will not or unable to use your provided client to access NTP server to get the time as it required another UDP client which is now not included in this library.

It is your job to set your device time manually before calling `Firebase.connect`.

In some devices, user needs to set the library reference time to use internally via function `Firebase.setSystemTime` except for ESP8266 and ESP32 devices that library can take the time from its timer directly.,

**Comment by mobizt** [comment]
The time `169445xxxx` is the epoch time of tomorrow.

**Comment by mobizt** [comment]
```cpp
Firebase.setSystemTime(1694425572); // Current Unix epoch Time

Serial.println(Firebase.getCurrentTime());
Serial.println(time(nullptr));
```

**Comment by mobizt** [comment]
The function `Firebase.setSystemTime` should return true for valid time set.

You should write your code carefully to prevent such human error.

**Comment by back920096** [comment]
![image](https://github.com/mobizt/ESP_SSLClient/assets/28179698/2808a15c-ce97-4083-8c8f-872a48bc737c)
I use Firebase.setSystemTime which always returns 0
But Serial.println(Firebase.getCurrentTime());
     Serial.println(time(nullptr));
It shows that there is writing, but it still jumps. Token error: code: -115
![image](https://github.com/mobizt/ESP_SSLClient/assets/28179698/bdf65742-fd3e-4be2-ab45-5045cbbc8349)

**Comment by mobizt** [comment]
Ok I will check this and update.

**Comment by mobizt** [comment]
Now you can update library to v4.4.2 with this issue fixed.

**Comment by back920096** [comment]
Thanks to the author. Successfully connected.
![image](https://github.com/mobizt/ESP_SSLClient/assets/28179698/57580d15-69a8-4052-a45b-2aab7ebd54ea)
![image](https://github.com/mobizt/ESP_SSLClient/assets/28179698/eb9471d4-d8d6-4219-9ab0-4ac5da01e114)
Is there any way to avoid clogging after unplugging the network cable?
I have tried using Firebase.reconnectWiFi(false) and it still gets blocked.

**Comment by back920096** [comment]
![image](https://github.com/mobizt/ESP_SSLClient/assets/28179698/abaf9b33-b521-4165-9219-80817a4173d8)
![image](https://github.com/mobizt/ESP_SSLClient/assets/28179698/eb5e1eaf-8f50-4973-b765-a0299959192f)
![image](https://github.com/mobizt/ESP_SSLClient/assets/28179698/132d6784-caa0-423a-adf0-2cf3b74924d0)
Report an error using fbdo.setExternalClient

**Comment by mobizt** [comment]
It quite off topic here.

When using `setEthernetClient` There is 60 seconds waiting time for DHCP as long as `Firebase.ready()` was executed. 

The function `reconnectWiFi` is applied only for WiFi and external client with network connection callback function.

The network connection callback function should do appropriate network disconnection first.

For GSM and Ethernet integration (`setEthernetClient`  and `setGSMClient`), the network reconnection was self-controlled and done automatically without user consent which is the library purpose. 

You have two choices in your case.

1. Use `setGenericClient` with callbacks (formerly `setExternalClient` and callbacks)
2. Temporary exclude `Firebase.ready()` from loop and pause the FirebaseData object with `pauseFirebase(true)` when you want to stop library to connect to server.

### For Client
The client is generic/basic/plain network Arduino Client instead of SSL Client.

Please see the Readme and examples for new version.

**Comment by mobizt** [comment]
> Report an error using fbdo.setExternalClient

Thanks for the bug report.  I will check and update.

**Comment by back920096** [comment]
fbdo.setGenericClient has the same error
![image](https://github.com/mobizt/ESP_SSLClient/assets/28179698/ed9715cd-0cc6-4692-a3f7-d9923a0fd999)
![image](https://github.com/mobizt/ESP_SSLClient/assets/28179698/7db36ca3-668b-4ff2-b06f-f30d29842193)
![image](https://github.com/mobizt/ESP_SSLClient/assets/28179698/64d35104-c8e7-461e-b16d-4a399d402ca4)

**Comment by mobizt** [comment]
I know it.

**Comment by mobizt** [comment]
Now you can update the library to fix the issue.

**Comment by back920096** [comment]
Already running normally
I'm happy to help you find the bug

**Comment by mobizt** [comment]
Thanks, the issue is usually found as the main library core has changed with huge improvement in memory and performance in v4.4.x.
